version: "2"
run:
  timeout: 5m
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    gosec:
      excludes:
        - G404
        - G101
    misspell:
      ignore-rules:
        - adres
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: web/internal/templatex/
      - linters:
          - all
        path: internal/adapters/persistence/postgres/db/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/zatrano/gocore
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
