//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	root := flag.String("root", "", "downloaded GoUI module directory")
	flag.Parse()
	if *root == "" {
		out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/zatrano/goui").Output()
		if err != nil {
			panic(err)
		}
		*root = strings.TrimSpace(string(out))
	}

	files := map[string]string{}
	add := func(route, relative string) {
		data, err := os.ReadFile(filepath.Join(*root, filepath.FromSlash(relative)))
		if err != nil {
			panic(err)
		}
		files[route] = string(data)
	}
	add("/client/goui.js", "client/goui.js")
	add("/forms/style.css", "forms/style.css")

	modules, err := filepath.Glob(filepath.Join(*root, "client", "modules", "*.js"))
	if err != nil {
		panic(err)
	}
	for _, path := range modules {
		add("/client/modules/"+filepath.Base(path), "client/modules/"+filepath.Base(path))
	}
	files["/goui/assets/app.css"] = appCSS

	keys := make([]string, 0, len(files))
	for key := range files {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var out bytes.Buffer
	out.WriteString("// Code generated by assets_generate.go; DO NOT EDIT.\n\npackage goui\n\nvar assetFiles = map[string]string{\n")
	for _, key := range keys {
		fmt.Fprintf(&out, "\t%s: %s,\n", strconv.Quote(key), strconv.Quote(files[key]))
	}
	out.WriteString("}\n")
	if err := os.WriteFile("assets_gen.go", out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

const appCSS = `
:root{
 color-scheme:dark;
 --primary:#11A8F4;--primary-hover:#0D97E2;--primary-active:#097ECC;--primary-light:#4CCBFF;--primary-glow:#37E7FF;--primary-subtle:#0E2437;
 --secondary:#1ED6FF;--secondary-hover:#00C7FF;--secondary-active:#00B0E5;
 --bg:#030914;--surface:#071523;--surface-2:#0C1E30;--hover:#12283E;--card:#0C1E30;
 --text:#F5F7FA;--text-secondary:#AAB8C7;--muted:#6D7C91;--disabled:#485567;
 --border:#1B3B55;
 --ok:#12D98A;--ok-hover:#0FC47B;--ok-subtle:#0A2A22;--danger:#FF5A6B;--danger-hover:#E84A5A;--danger-subtle:#2A1218;
 --warning:#F5B841;--warning-subtle:#2A2210;--info:#27C8FF;--info-subtle:#0A2430;
 --sidebar-bg:#04101D;--sidebar-active:#0E2437;--sidebar-hover:#0B1C2E;--sidebar-border:#133149;--sidebar-icon:#19B7FF;
 --input-bg:#091827;--input-border:#1B3D59;--input-focus:#14B5FF;--input-placeholder:#6F8197;--input-text:#EEF4FA;
 --radius-control:.875rem;--radius-container:.875rem;
 --shadow-card:0 0 0 1px #1B3B5540;
 --shadow-raised:0 0 8px rgba(17,168,244,.35),0 0 25px rgba(17,168,244,.18);
 --glow:0 0 8px rgba(17,168,244,.35),0 0 25px rgba(17,168,244,.18);
 --gradient-main:linear-gradient(135deg,#0A6EFF 0%,#11A8F4 45%,#37E7FF 100%);
 --gradient-hero:linear-gradient(180deg,#030914 0%,#071523 100%);
 --chart-1:#11A8F4;--chart-2:#27C8FF;--chart-3:#12D98A;--chart-4:#F5B841;--chart-5:#FF5A6B;--chart-6:#9B7BFF;--chart-7:#00E5D4;--chart-8:#4CCBFF;
 --color-goui-primary:var(--primary);--color-goui-border:var(--border);
 --color-goui-error:var(--danger);--color-goui-success:var(--ok);
 --color-goui-warning:var(--warning);--color-goui-info:var(--info);
 --color-goui-text:var(--text);--color-goui-surface:var(--surface);
 --radius-goui:var(--radius-control);--spacing-goui-field:.75rem
}
*,*::before,*::after{box-sizing:border-box}
html{-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}
body{margin:0;min-height:100vh;background:var(--bg);color:var(--text);font:14px/1.5 Figtree,ui-sans-serif,system-ui,sans-serif,"Apple Color Emoji","Segoe UI Emoji"}
.brand-wordmark{font-family:Audiowide,ui-sans-serif,system-ui,sans-serif;font-weight:400;letter-spacing:.06em;text-transform:uppercase;color:var(--primary);line-height:1}
.brand-wordmark--sm{font-size:.7rem;letter-spacing:.08em}
a{color:var(--primary);text-decoration:none;transition:color .15s ease-out}
a:hover{color:var(--primary-light)}
:focus-visible{outline:2px solid #11A8F466;outline-offset:2px}
h1,h2,h3{margin-top:0;color:var(--text)}
h1{font-size:1.5rem;line-height:1.25;font-weight:600;letter-spacing:-.025em}
h2{font-size:1.125rem;font-weight:600}h3{font-size:1rem;font-weight:500}
p{margin-top:0}code,pre,kbd,samp{font-family:"JetBrains Mono",ui-monospace,SFMono-Regular,Consolas,monospace}
code{border-radius:var(--radius-control);background:var(--surface-2);padding:.125rem .375rem;font-size:.8125rem}
button,input,select,textarea{font:inherit}
button{cursor:pointer}

.gocore-shell{min-height:100vh;background:var(--gradient-hero)}
.gocore-header{position:sticky;top:0;z-index:30;display:flex;min-height:4rem;align-items:center;justify-content:space-between;gap:2rem;padding:.75rem max(1.25rem,calc((100% - 72rem)/2));border-bottom:1px solid var(--border);background:#071523ed;box-shadow:none;backdrop-filter:blur(12px)}
.gocore-header .brand{display:inline-flex;align-items:center;gap:.625rem;color:var(--text);text-decoration:none}
.gocore-header .brand .brand-wordmark{font-size:1.25rem}
.gocore-header nav{display:flex;align-items:center;justify-content:flex-end;gap:.25rem;flex-wrap:wrap}
.gocore-header nav>a,.link-button{display:inline-flex;min-height:2.5rem;align-items:center;border:0;border-radius:var(--radius-control);padding:.5rem .75rem;background:transparent;color:var(--muted);font-weight:500;transition:background-color .15s,color .15s}
.gocore-header nav>a:hover,.link-button:hover{background:var(--hover);color:var(--text)}
.gocore-header nav>a[href="/auth/register"],
.gocore-header nav>a[href="/dashboard"]{background:var(--gradient-main);color:#fff;padding-inline:1rem;box-shadow:var(--glow);transition:box-shadow .2s ease,filter .2s ease}
.gocore-header nav>a[href="/auth/register"]:hover,
.gocore-header nav>a[href="/dashboard"]:hover{background:var(--gradient-main);color:#fff;filter:brightness(1.08);box-shadow:0 0 14px rgba(17,168,244,.5)}
.gocore-main{width:min(72rem,calc(100% - 2rem));margin:0 auto;padding:2rem 0 4rem}
.lang-switch{display:inline-flex;align-items:center}
.lang-switch__select{appearance:none;-webkit-appearance:none;min-height:2.25rem;border:1px solid var(--border);border-radius:var(--radius-control);background-color:var(--input-bg);background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3E%3Cpath stroke='%236D7C91' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='m6 8 4 4 4-4'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 0.75rem center;background-size:1rem;padding:.35rem 2.25rem .35rem .65rem;color:var(--text);font-size:.75rem;font-weight:500;line-height:1.2;box-shadow:none;cursor:pointer}
.lang-switch__select:focus{border-color:var(--input-focus);outline:0;box-shadow:0 0 0 3px #11A8F433}
.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}

.card,.panel,.auth-card,.contact-info{border:1px solid var(--border);border-radius:var(--radius-container);background:var(--card);padding:1.5rem;box-shadow:var(--shadow-card)}
.card{margin-bottom:1.25rem}
.card>h1:first-child,.card>h2:first-child,.panel>h1:first-child{margin-bottom:1.25rem}
.panel-header{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:1.25rem}
.panel-header h1,.panel-header h2{margin:0}
.grid{display:grid;gap:1.25rem}.grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}
.stat{display:flex;min-height:8rem;flex-direction:column;justify-content:center;gap:.35rem;border:1px solid var(--border);border-radius:var(--radius-container);background:var(--card);padding:1.5rem;box-shadow:var(--shadow-card)}
.stat strong{font-size:1.25rem;font-weight:600}.muted{color:var(--muted)}
.actions{display:flex;align-items:center;gap:.625rem;flex-wrap:wrap}
.stack{display:grid;gap:1rem}.mb-4{margin-bottom:1rem}.text-center{text-align:center}.text-xs{font-size:.75rem}
.page-header{display:flex;min-height:2.5rem;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:1.25rem}
.page-header h1{margin:0}
.dashboard-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-bottom:1.25rem}
.dashboard-stats .stat{min-width:0;min-height:7rem;flex-direction:row;align-items:center;justify-content:flex-start;gap:1rem}
.dashboard-stats .stat>div{display:flex;min-width:0;flex-direction:column}
.dashboard-stats .stat strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.dashboard-stats .stat p{margin:0}
.stat-icon{display:inline-flex;width:2.75rem;height:2.75rem;flex-shrink:0;align-items:center;justify-content:center;border-radius:var(--radius-control);background:var(--primary-subtle);color:var(--primary-light);box-shadow:0 0 12px rgba(17,168,244,.2)}
.stat-icon svg{display:block;width:1.35rem;height:1.35rem;fill:none;stroke:currentColor;stroke-width:1.75;stroke-linecap:round;stroke-linejoin:round}
.dashboard-welcome{display:flex;align-items:center;justify-content:space-between;gap:1.5rem}
.dashboard-welcome h2{margin-bottom:.25rem}.dashboard-welcome p{margin:0}

.form-row,.form-field{display:grid;gap:.4rem;margin-bottom:1rem}
.account-settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}
.account-settings-grid>form{
 margin:0;padding:1rem;border:1px solid var(--border);border-radius:var(--radius-control);background:transparent;
 display:flex;flex-direction:column;min-height:100%
}
.account-settings-grid>form h3{margin:0 0 .65rem;font-size:.875rem;font-weight:600}
.account-settings-grid>form .form-row{margin-bottom:.65rem}
.account-settings-grid>form .muted{margin:0 0 .65rem}
.account-settings-grid>form button{align-self:flex-start;margin-top:auto}
.account-settings-span{grid-column:1/-1}
.form-row label,.form-field label{font-size:.875rem;font-weight:500;color:var(--text)}
.form-row input,.form-row textarea,.form-control:not(select){
 width:100%;min-height:2.75rem;border:1px solid var(--input-border);border-radius:var(--radius-control);
 background:var(--input-bg);padding:.625rem .875rem;color:var(--input-text);box-shadow:none;
 transition:border-color .15s ease-out,box-shadow .15s ease-out
}
.form-row select,
.form-field select,
select.form-control,
select.form-select{
 width:100%;min-height:2.75rem;border:1px solid var(--input-border);border-radius:var(--radius-control);
 color:var(--input-text);box-shadow:none;cursor:pointer;
 appearance:none;-webkit-appearance:none;-moz-appearance:none;
 background-color:var(--input-bg);
 background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3E%3Cpath stroke='%236D7C91' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='m6 8 4 4 4-4'/%3E%3C/svg%3E");
 background-repeat:no-repeat;
 background-position:right 1rem center;
 background-size:1.05rem;
 padding:.625rem 2.75rem .625rem .875rem;
 transition:border-color .15s ease-out,box-shadow .15s ease-out
}
.form-row select::-ms-expand,
.form-field select::-ms-expand,
select.form-control::-ms-expand,
select.form-select::-ms-expand{display:none}
.form-row textarea,.form-field textarea{min-height:7rem;resize:vertical}
.form-row input::placeholder,.form-control::placeholder{color:var(--input-placeholder)}
.form-row input:focus,.form-row select:focus,.form-row textarea:focus,.form-control:focus,.form-select:focus{border-color:var(--input-focus);outline:0;box-shadow:0 0 0 3px #14B5FF33,0 0 12px rgba(17,168,244,.2)}
.form-section{margin-top:1.25rem;border-top:1px solid var(--border);padding-top:1.25rem}
.form-section__title{margin-bottom:1rem;font-size:1rem;font-weight:600}
.checkbox-list{display:grid;gap:.5rem}
.field-error{margin:.25rem 0 0;color:var(--danger);font-size:.8125rem}
.users-filter-card{padding:1rem 1.25rem}
.users-filter-card>h2:first-child{margin-bottom:.75rem;font-size:1rem}
.users-filter-grid{display:flex;align-items:flex-end;gap:.75rem;flex-wrap:wrap}
.users-filter-grid .form-row{min-width:0;margin-bottom:0}
.users-filter-search{flex:2 1 15rem}.users-filter-role{flex:1 1 10rem}
.users-filter-select{flex:1 1 10rem}.users-filter-limit{flex:0 1 6rem}
.users-filter-clear{flex:0 0 auto}
.audit-lead{margin-top:-.75rem;margin-bottom:1rem}
.audit-filter-card{padding:1rem 1.25rem}
.audit-filter-card>h2:first-child{margin-bottom:.75rem;font-size:1rem}
.audit-filter-grid{display:flex;align-items:flex-end;gap:.75rem;flex-wrap:wrap}
.audit-filter-grid .form-field,.audit-filter-grid .form-row{min-width:0;margin-bottom:0;flex:1 1 10rem}
.audit-filter-grid .form-field:first-child{flex:2 1 14rem}
.audit-filter-grid button{flex:0 0 auto}

.button,.btn,button:where(:not(.link-button):not(.goui-upload-carrier)){
 display:inline-flex;min-height:2.75rem;align-items:center;justify-content:center;gap:.5rem;
 border:1px solid transparent;border-radius:var(--radius-control);padding:.625rem 1rem;
 background:var(--gradient-main);color:#fff;font-weight:500;line-height:1.25;
 box-shadow:var(--glow);transition:box-shadow .2s ease,filter .2s ease,border-color .2s ease,color .2s ease
}
.button:hover,.btn:hover,button:where(:not(.link-button):not(.goui-upload-carrier)):hover{
 background:var(--gradient-main);color:#fff;filter:brightness(1.08);box-shadow:0 0 14px rgba(17,168,244,.5)
}
.button.secondary,.btn.secondary,button.secondary{border-color:var(--border);background:var(--surface-2);color:var(--text);box-shadow:none;filter:none}
.button.secondary:hover,.btn.secondary:hover,button.secondary:hover{background:var(--hover);color:var(--text);filter:none;box-shadow:none}
.button.danger,.btn.danger,button.danger{background:var(--danger);box-shadow:0 0 8px rgba(255,90,107,.3);filter:none}
.button.danger:hover,.btn.danger:hover,button.danger:hover{background:var(--danger-hover);filter:none}
.button.active,button.active{border-color:var(--primary);background:var(--primary-subtle);color:var(--primary-light);box-shadow:none;filter:none}
.button:disabled,.btn:disabled,button:disabled{cursor:not-allowed;opacity:.5;box-shadow:none}
.button.sm,.btn.sm,button.sm,a.button.sm{
 min-height:1.75rem;padding:.25rem .55rem;font-size:.75rem;font-weight:500;line-height:1.2;box-shadow:none
}
a.button{text-decoration:none}
.table-actions{display:flex;align-items:center;gap:.375rem;flex-wrap:nowrap;justify-content:flex-end}
.table-actions .button,.table-actions .btn,.table-actions button:where(:not(.link-button)){
 min-height:1.5rem;padding:.15rem .45rem;font-size:.6875rem;line-height:1.15;white-space:nowrap;box-shadow:none
}
.table-actions .table-action-form{display:inline-flex;margin:0;padding:0;border:0;background:transparent}
.table-actions form{display:inline-flex;margin:0}

.alert{margin-bottom:1.25rem;border:1px solid;padding:.875rem 1rem;border-radius:var(--radius-container);font-size:.875rem}
.alert.success{border-color:#12D98A44;background:var(--ok-subtle);color:#12D98A}
.alert.error{border-color:#FF5A6B44;background:var(--danger-subtle);color:#FF5A6B}
.alert.warning{border-color:#F5B84144;background:var(--warning-subtle);color:#F5B841}
.badge{display:inline-flex;align-items:center;border-radius:999px;background:var(--primary-subtle);padding:.2rem .625rem;color:var(--primary-light);font-size:.75rem;font-weight:500}
.badge.ok{background:var(--ok-subtle);color:#12D98A}.badge.muted{background:var(--surface-2);color:var(--muted)}

.data-table,table{width:100%;border-collapse:collapse;background:var(--card);font-size:.875rem}
th{border-bottom:1px solid var(--border);background:#0C1E30;padding:.625rem 1rem;text-align:left;color:var(--muted);font-size:.75rem;font-weight:500;text-transform:uppercase;letter-spacing:.025em}
td{border-bottom:1px solid var(--border);padding:.75rem 1rem;vertical-align:middle;color:var(--text)}
tbody tr:last-child td{border-bottom:0}tbody tr:hover td{background:var(--hover)}
.card table,.panel table{margin-inline:-1.5rem;width:calc(100% + 3rem)}
.table-wrap{overflow-x:auto;-webkit-overflow-scrolling:touch}
.pagination{display:flex;align-items:center;justify-content:flex-end;gap:.375rem;margin-top:1rem}
.pagination button{min-width:2.25rem;min-height:2.25rem;padding:.375rem .625rem}

.landing{position:relative;overflow:hidden;padding:4rem 0 2rem;text-align:center}
.landing::before,.landing::after{content:"";position:absolute;z-index:0;border-radius:999px;filter:blur(64px);pointer-events:none}
.landing::before{top:-5rem;left:5%;width:18rem;height:18rem;background:#11A8F428}
.landing::after{top:5rem;right:5%;width:20rem;height:20rem;background:#37E7FF1a}
.landing>*{position:relative;z-index:1}.landing-hero{max-width:48rem;margin:0 auto}
.landing-hero h1{margin-bottom:1.5rem;font-size:3.25rem;line-height:1.1;letter-spacing:-.04em}
.landing-hero>p{max-width:42rem;margin:0 auto 2rem;color:var(--text-secondary);font-size:1.125rem;line-height:1.65}
.landing-actions{display:flex;align-items:center;justify-content:center;gap:.75rem;flex-wrap:wrap}
.landing-features{margin-top:5rem}.feature-list{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1.5rem;padding:0;list-style:none;text-align:left}
.feature-list li{border:1px solid var(--border);border-radius:var(--radius-container);background:var(--card);padding:1.5rem;box-shadow:var(--shadow-card);transition:transform .2s,box-shadow .2s,border-color .2s}
.feature-list li:hover{transform:translateY(-2px);border-color:#11A8F466;box-shadow:var(--glow)}
.feature-list h2,.feature-list h3{margin-bottom:.5rem}.feature-list p{margin:0;color:var(--muted)}

.auth-card{width:min(28rem,100%);margin:2rem auto}
.auth-card>h1{text-align:center}.auth-card>.muted{text-align:center}
.auth-oauth-section{display:grid;gap:.75rem;margin-bottom:1rem}
.oauth-list{display:grid;gap:.625rem}
.oauth-btn{display:inline-flex;width:100%;min-height:2.75rem;align-items:center;justify-content:center;gap:.625rem;border:1px solid var(--border);border-radius:var(--radius-control);background:var(--surface-2);padding:.625rem 1rem;color:var(--text);font-weight:500;line-height:1.25;box-shadow:none;transition:background-color .15s,border-color .15s}
.oauth-btn:hover{background:var(--hover);color:var(--text);border-color:#11A8F466}
.oauth-btn__icon{display:block;width:1.125rem;height:1.125rem;flex-shrink:0}
.auth-oauth-divider{display:flex;align-items:center;gap:.75rem}
.auth-oauth-divider>span{height:1px;flex:1;background:var(--border)}
.auth-oauth-divider>strong{color:var(--muted);font-size:.8125rem;font-weight:400}
.contact-info{margin-top:1.25rem}.contact-info ul{display:grid;gap:.75rem;padding:0;list-style:none}
.contact-info li{border-bottom:1px solid var(--border);padding-bottom:.75rem}

dl{margin:0}dl>div{display:grid;grid-template-columns:11rem 1fr;gap:1rem;border-bottom:1px solid var(--border);padding:.875rem 0}
dl>div:last-child{border-bottom:0}dt{color:var(--muted);font-weight:500}dd{margin:0}
.notif-list,.goui-upload-list{display:grid;gap:.75rem;padding:0;list-style:none}
.notif-item{border:1px solid var(--border);border-radius:var(--radius-container);background:var(--card);padding:1rem;box-shadow:var(--shadow-card)}
.notif-item.unread{border-left:4px solid var(--primary);background:#0E2437}
.goui-upload{border:1px solid var(--border);border-radius:var(--radius-container);background:var(--surface-2);padding:1rem}
.goui-upload-drop{display:grid;place-items:center;min-height:8rem;border:1px dashed var(--border);border-radius:var(--radius-control);background:var(--input-bg);padding:1.25rem;text-align:center}
.goui-upload-hint{margin-bottom:.75rem;color:var(--muted)}.goui-upload-size{color:var(--muted);font-size:.75rem}

.auth-shell{position:relative;overflow:hidden;background:var(--gradient-hero)}
.auth-shell::before,.auth-shell::after{content:"";position:fixed;border-radius:999px;filter:blur(72px);pointer-events:none}
.auth-shell::before{top:-8rem;left:-7rem;width:24rem;height:24rem;background:#11A8F422}
.auth-shell::after{right:-8rem;bottom:-10rem;width:28rem;height:28rem;background:#37E7FF14}
.auth-shell-backdrop{position:relative;z-index:1;display:flex;min-height:100vh;align-items:center;justify-content:center;padding:2rem 1rem}
.auth-shell-content{width:100%;max-width:28rem}
.auth-brand{display:flex;width:max-content;align-items:center;justify-content:center;gap:.625rem;color:var(--text);text-decoration:none}
.auth-brand:hover{color:var(--text)}
.auth-brand .brand-wordmark{font-size:1.35rem}
.auth-shell-top{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin:0 auto 2rem}
.auth-shell-top .auth-brand{margin:0}
.auth-shell .auth-card{width:100%;margin:0;border-radius:var(--radius-container);padding:2rem;box-shadow:var(--glow);border-color:#11A8F440}
.auth-shell .auth-card>h1{margin-bottom:.5rem;text-align:center}
.auth-shell .auth-card>h1+.muted{margin-bottom:1.5rem;text-align:center}
.auth-shell .auth-card .stack{gap:0}
.auth-shell .auth-card .stack>.form-row,.auth-shell .auth-card .stack>.form-field{margin-bottom:1rem}
.auth-shell .auth-card .stack>.btn,.auth-shell .auth-card .stack>button[type="submit"]{width:100%;margin-top:.25rem}
.auth-shell .auth-card>p:last-child{margin:1.25rem 0 0;text-align:center}
.auth-links{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-top:1.25rem;font-size:.875rem}
.auth-links-single{justify-content:center;text-align:center}
.auth-links a{color:var(--muted)}
.auth-links a:hover{color:var(--primary)}
.auth-shell .oauth-list .oauth-btn{width:100%}
.auth-shell .alert{margin-bottom:1rem}
.mfa-qr{display:block;max-width:100%;height:auto;margin:1rem auto;border:1px solid var(--border);border-radius:var(--radius-control);background:#fff;padding:.5rem}
.recovery-code-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.5rem;margin:1rem 0;padding:0;list-style:none}
.recovery-code-list li{border:1px solid var(--border);border-radius:var(--radius-control);background:var(--surface-2);padding:.625rem;text-align:center}
.recovery-code-list code{font-size:.875rem}

.panel-shell{display:flex;height:100vh;overflow:hidden;background:var(--bg)}
.panel-workspace{display:flex;min-width:0;min-height:0;flex:1;flex-direction:column;overflow:hidden}
.panel-shell .gocore-header{position:relative;top:auto;z-index:20;min-height:4rem;flex-shrink:0;padding:.625rem 1.5rem;border-bottom:1px solid var(--border);background:var(--surface);box-shadow:none;backdrop-filter:none}
.panel-shell .gocore-main{width:100%;max-width:none;min-height:0;flex:1;margin:0;padding:1.5rem;overflow-x:hidden;overflow-y:auto}
.shell-panel-topbar__start,.shell-panel-topbar__actions{display:flex;align-items:center;gap:.75rem}
.shell-panel-topbar__start{min-width:0;flex:1}.shell-panel-topbar__actions{justify-content:flex-end}
.shell-panel-topbar__actions .lang-switch{margin-right:.125rem}
.panel-page-title{display:flex;min-width:0;flex-direction:column;line-height:1.2}
.panel-page-title span{color:var(--muted);font-size:.7rem;font-weight:500;text-transform:uppercase;letter-spacing:.08em}
.panel-page-title .brand-wordmark{color:var(--primary);margin-bottom:.15rem}
.panel-page-title strong{overflow:hidden;color:var(--text);font-size:.95rem;font-weight:600;text-overflow:ellipsis;white-space:nowrap}
.ui-icon-btn.ui-icon-btn{display:inline-flex;position:relative;width:2.75rem;height:2.75rem;min-height:2.75rem;flex-shrink:0;align-items:center;justify-content:center;border:1px solid var(--border);border-radius:999px;background:var(--surface-2);padding:0;color:var(--muted);box-shadow:none}
.ui-icon-btn.ui-icon-btn:hover{background:var(--hover);color:var(--primary-light);border-color:#11A8F466}
.ui-icon-btn svg,.nav-icon svg,.sidebar-user-icon svg{display:block;width:1.25rem;height:1.25rem;fill:none;stroke:currentColor;stroke-width:1.75;stroke-linecap:round;stroke-linejoin:round}
.notif-bell__badge{
 position:absolute;top:0;right:0;z-index:1;
 display:inline-flex;min-width:1.125rem;height:1.125rem;align-items:center;justify-content:center;
 border:2px solid var(--surface);border-radius:999px;background:var(--primary);padding:0 .3rem;
 color:#fff;font-size:.65rem;font-weight:700;line-height:1;pointer-events:none;
 transform:translate(40%,-40%);box-shadow:0 0 8px rgba(17,168,244,.45)
}
.notif-bell__badge[hidden]{display:none!important}
@keyframes notif-bell-ring{
 0%{transform:rotate(0)}
 12%{transform:rotate(14deg)}
 24%{transform:rotate(-12deg)}
 36%{transform:rotate(10deg)}
 48%{transform:rotate(-8deg)}
 60%{transform:rotate(6deg)}
 72%{transform:rotate(-4deg)}
 100%{transform:rotate(0)}
}
.notif-bell.notif-bell--ring svg{transform-origin:top center;animation:notif-bell-ring .85s ease-in-out}
.shell-panel-topbar__actions .ui-btn--sm{min-height:2.25rem;padding:.45rem .8rem;font-size:.75rem}
.mobile-menu-button{display:inline-flex}.sidebar-close{display:inline-flex}

.shell-panel-sidebar{position:fixed;inset:0 auto 0 0;z-index:50;display:flex;width:18.125rem;max-width:85vw;flex-direction:column;overflow-y:auto;border-right:1px solid var(--sidebar-border);background:var(--sidebar-bg);padding:0 1.25rem;transform:translateX(-100%);transition:transform .3s ease-out}
.sidebar-header{display:flex;min-height:4rem;flex-shrink:0;align-items:center;justify-content:space-between;gap:.75rem;margin-inline:-1.25rem;padding-inline:1.25rem;border-bottom:1px solid var(--sidebar-border)}
.sidebar-brand{display:inline-flex;min-width:0;align-items:center;gap:.625rem;color:var(--text);text-decoration:none}
.sidebar-brand:hover{color:var(--text)}
.sidebar-brand .brand-wordmark{font-size:1.15rem}
.brand-mark{display:grid;width:2rem;height:2rem;flex-shrink:0;place-items:center;border-radius:.625rem;background:var(--gradient-main);color:#fff;font-family:Audiowide,ui-sans-serif,system-ui,sans-serif;font-size:.95rem;font-weight:400;box-shadow:var(--glow)}
.sidebar-nav{display:flex;flex:1;flex-direction:column;gap:.25rem;overflow-y:auto;padding:1rem 0 1.5rem}
.sidebar-nav-link{display:flex;align-items:center;gap:.75rem;border-radius:var(--radius-control);padding:.55rem .75rem;color:var(--muted);font-size:.875rem;font-weight:500;transition:background-color .15s,color .15s}
.sidebar-nav-link:hover{background:var(--sidebar-hover);color:var(--text)}
.sidebar-nav-link--active,.sidebar-nav-link--active:hover{background:var(--sidebar-active);color:var(--sidebar-icon)}
.sidebar-nav-link--active .nav-icon,.sidebar-nav-link--active:hover .nav-icon{color:var(--sidebar-icon)}
.sidebar-nav-group{margin:0}
.sidebar-nav-group__toggle{list-style:none;cursor:pointer;user-select:none}
.sidebar-nav-group__toggle::-webkit-details-marker{display:none}
.sidebar-nav-group__toggle .sidebar-nav-chevron{margin-left:auto;display:inline-flex;color:var(--muted);transition:transform .15s}
.sidebar-nav-group__toggle .sidebar-nav-chevron svg{width:1rem;height:1rem}
.sidebar-nav-group[open]>.sidebar-nav-group__toggle .sidebar-nav-chevron{transform:rotate(180deg)}
.sidebar-nav-group[open]>.sidebar-nav-group__toggle{color:var(--text)}
.sidebar-nav-sub{
 display:flex;flex-direction:column;gap:.125rem;
 margin:.35rem 0 .5rem 0;margin-left:1.35rem;padding:.35rem 0 .15rem .85rem;
 border-left:2px solid var(--sidebar-border)
}
.sidebar-nav-sub .sidebar-nav-link{
 gap:.5rem;padding:.35rem .55rem;color:var(--muted);font-size:.78rem;font-weight:450
}
.sidebar-nav-sub .sidebar-nav-link .nav-icon{width:1rem;flex-shrink:0}
.sidebar-nav-sub .sidebar-nav-link .nav-icon svg{width:1rem;height:1rem}
.sidebar-nav-sub .sidebar-nav-link--active,
.sidebar-nav-sub .sidebar-nav-link--active:hover{
 background:var(--sidebar-active);color:var(--sidebar-icon);font-weight:500
}
.nav-icon{display:inline-flex;width:1.5rem;height:1.5rem;flex-shrink:0;align-items:center;justify-content:center}
.sidebar-footer{margin-top:auto;margin-inline:-1.25rem;border-top:1px solid var(--sidebar-border);padding:1.25rem}
.sidebar-user{display:flex;min-width:0;align-items:center;gap:.75rem}
.sidebar-user-icon{display:inline-flex;width:2.5rem;height:2.5rem;flex-shrink:0;align-items:center;justify-content:center;border-radius:999px;background:var(--primary-subtle);color:var(--sidebar-icon)}
.sidebar-user-copy{display:flex;min-width:0;flex:1;flex-direction:column}
.sidebar-user-copy strong,.sidebar-user-copy span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.sidebar-user-copy strong{font-size:.875rem;font-weight:500;text-transform:capitalize}.sidebar-user-copy span{margin-top:.125rem;color:var(--muted);font-size:.75rem}
.shell-panel-overlay{position:fixed;inset:0;z-index:40;display:none;width:100%;height:100%;min-height:0;border:0;border-radius:0;background:#030914cc;padding:0;box-shadow:none;backdrop-filter:blur(8px)}
.shell-panel-overlay:hover{background:#030914cc}
body.sidebar-open .shell-panel-sidebar{transform:translateX(0)}
body.sidebar-open .shell-panel-overlay{display:block}

@media(min-width:1280px){
 .shell-panel-sidebar{position:static;z-index:auto;max-width:none;flex-shrink:0;transform:translateX(0)}
 .shell-panel-overlay,.sidebar-close,.mobile-menu-button{display:none!important}
}
@media(max-width:800px){
 .gocore-header{position:static;align-items:flex-start;flex-direction:column;gap:.75rem;padding:1rem}
 .gocore-header nav{width:100%;justify-content:flex-start}
 .gocore-main{width:min(100% - 1.5rem,72rem);padding-top:1.25rem}
 .panel-shell .gocore-header{min-height:4rem;align-items:center;flex-direction:row;gap:1rem;padding:.625rem 1rem}
 .panel-shell .gocore-main{width:100%;padding:1rem}
 .grid.two,.feature-list,.dashboard-stats,.account-settings-grid{grid-template-columns:1fr}
 .dashboard-welcome{align-items:flex-start;flex-direction:column}
 .landing{padding-top:2.5rem}.landing-hero h1{font-size:2.25rem}
 .card,.panel,.auth-card,.contact-info{padding:1.25rem}
 .auth-shell-backdrop{padding:1.25rem .75rem}
 .auth-shell .auth-card{padding:1.5rem}
 .auth-shell-top{margin-bottom:1.5rem}
 .users-filter-grid{display:grid;grid-template-columns:1fr 1fr}
 .users-filter-search{grid-column:1/-1}
 .users-filter-clear{width:100%}
 .audit-filter-grid{display:grid;grid-template-columns:1fr 1fr}
 .audit-filter-grid .form-field:first-child{grid-column:1/-1}
 .audit-filter-grid button{width:100%}
 .recovery-code-list{grid-template-columns:1fr}
 .card table,.panel table{display:block;width:calc(100% + 2.5rem);margin-inline:-1.25rem;overflow-x:auto}
 dl>div{grid-template-columns:1fr;gap:.25rem}
}
@media(max-width:520px){
 .users-filter-grid{grid-template-columns:1fr}
 .users-filter-search{grid-column:auto}
 .audit-filter-grid{grid-template-columns:1fr}
 .audit-filter-grid .form-field:first-child{grid-column:auto}
}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition-duration:.01ms!important;animation-duration:.01ms!important}}
`
