// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec

INSERT INTO audit_logs (id, actor_id, action, resource, resource_id, ip, user_agent, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAuditLogParams struct {
	ID         uuid.UUID          `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	ResourceID pgtype.Text        `json:"resource_id"`
	Ip         *netip.Addr        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// audit_logs için type-safe sorgular.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, actor_id, action, resource, resource_id, ip, user_agent, metadata, created_at
FROM audit_logs
WHERE actor_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditLogsByActorParams struct {
	ActorID *uuid.UUID `json:"actor_id"`
	Limit   int32      `json:"limit"`
}

type ListAuditLogsByActorRow struct {
	ID         uuid.UUID          `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	ResourceID pgtype.Text        `json:"resource_id"`
	Ip         *netip.Addr        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Aktöre göre denetim kaydı listeleme (en yeni önce), index'li.
func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]ListAuditLogsByActorRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor, arg.ActorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByActorRow{}
	for rows.Next() {
		var i ListAuditLogsByActorRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
