// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthToken = `-- name: CreateAuthToken :one

INSERT INTO auth_tokens (id, user_id, purpose, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, user_id, purpose, token_hash, expires_at, used_at, created_at
`

type CreateAuthTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Purpose   string             `json:"purpose"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// auth_tokens: tek kullanımlık süreli token'lar (e-posta doğrulama, şifre sıfırlama).
// Ham token saklanmaz; yalnızca token_hash (SHA-256) tutulur.
func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthTokensForUser = `-- name: DeleteAuthTokensForUser :exec
DELETE FROM auth_tokens WHERE user_id = $1 AND purpose = $2
`

type DeleteAuthTokensForUserParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Purpose string    `json:"purpose"`
}

// Aynı amaçlı önceki token'ları geçersiz kılmak için (yeni token üretilirken).
func (q *Queries) DeleteAuthTokensForUser(ctx context.Context, arg DeleteAuthTokensForUserParams) error {
	_, err := q.db.Exec(ctx, deleteAuthTokensForUser, arg.UserID, arg.Purpose)
	return err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :exec
DELETE FROM auth_tokens WHERE expires_at < now() OR used_at IS NOT NULL
`

// Periyodik temizlik: süresi dolmuş veya kullanılmış token'ları siler.
func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthTokens)
	return err
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT id, user_id, purpose, token_hash, expires_at, used_at, created_at FROM auth_tokens WHERE token_hash = $1
`

func (q *Queries) GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, tokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :execrows
UPDATE auth_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL AND expires_at > now()
`

// Tek kullanım: yalnızca kullanılmamış ve süresi geçmemiş token işaretlenir.
func (q *Queries) MarkAuthTokenUsed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAuthTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
