// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID            uuid.UUID          `json:"id"`
	EventID       *uuid.UUID         `json:"event_id"`
	ActorID       *uuid.UUID         `json:"actor_id"`
	ActorType     string             `json:"actor_type"`
	ActorEmail    string             `json:"actor_email"`
	Action        string             `json:"action"`
	Resource      string             `json:"resource"`
	ResourceID    pgtype.Text        `json:"resource_id"`
	Ip            *netip.Addr        `json:"ip"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
	Source        string             `json:"source"`
	CorrelationID string             `json:"correlation_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuthToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Purpose   string             `json:"purpose"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ContactMessage struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Message   string             `json:"message"`
	Locale    string             `json:"locale"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent string             `json:"user_agent"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type IdempotencyKey struct {
	ID          uuid.UUID          `json:"id"`
	Scope       string             `json:"scope"`
	Key         string             `json:"key"`
	ActorID     string             `json:"actor_id"`
	RequestHash string             `json:"request_hash"`
	Status      string             `json:"status"`
	Response    []byte             `json:"response"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type MfaRecoveryCode struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID          uuid.UUID          `json:"id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Read        bool               `json:"read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

type OutboxJob struct {
	ID             uuid.UUID          `json:"id"`
	Kind           string             `json:"kind"`
	AggregateType  string             `json:"aggregate_type"`
	AggregateID    string             `json:"aggregate_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	LastError      pgtype.Text        `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Payment struct {
	ID                uuid.UUID          `json:"id"`
	Reference         string             `json:"reference"`
	Provider          string             `json:"provider"`
	Status            string             `json:"status"`
	Stage             string             `json:"stage"`
	Amount            string             `json:"amount"`
	PaidAmount        string             `json:"paid_amount"`
	Currency          string             `json:"currency"`
	Installment       int32              `json:"installment"`
	BuyerName         string             `json:"buyer_name"`
	BuyerSurname      string             `json:"buyer_surname"`
	BuyerEmail        string             `json:"buyer_email"`
	BuyerPhone        string             `json:"buyer_phone"`
	CardHolder        string             `json:"card_holder"`
	CardBin           string             `json:"card_bin"`
	CardLast4         string             `json:"card_last4"`
	CardAssociation   string             `json:"card_association"`
	ProviderPaymentID string             `json:"provider_payment_id"`
	ResultCode        string             `json:"result_code"`
	ResultMessage     string             `json:"result_message"`
	AuthCode          string             `json:"auth_code"`
	ConversationData  string             `json:"conversation_data"`
	InitPayload       string             `json:"init_payload"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type Permission struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	Name            string             `json:"name"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Active          bool               `json:"active"`
	EmailVerified   bool               `json:"email_verified"`
	MfaEnabled      bool               `json:"mfa_enabled"`
	MfaSecret       string             `json:"mfa_secret"`
	MfaLastUsedStep pgtype.Int8        `json:"mfa_last_used_step"`
	PreferredLocale string             `json:"preferred_locale"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
