// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByRecipient = `-- name: CountNotificationsByRecipient :one
SELECT COUNT(*)::bigint AS count
FROM notifications
WHERE recipient_id = $1
`

func (q *Queries) CountNotificationsByRecipient(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByRecipient, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) AS count FROM notifications
WHERE recipient_id = $1 AND read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (id, recipient_id, title, content, read, created_at, read_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, recipient_id, title, content, read, created_at, read_at
`

type CreateNotificationParams struct {
	ID          uuid.UUID          `json:"id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Read        bool               `json:"read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

// notifications tablosu için type-safe sorgular (uygulama içi bildirimler).
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.RecipientID,
		arg.Title,
		arg.Content,
		arg.Read,
		arg.CreatedAt,
		arg.ReadAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Title,
		&i.Content,
		&i.Read,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const deleteAllNotificationsByRecipient = `-- name: DeleteAllNotificationsByRecipient :execrows
DELETE FROM notifications
WHERE recipient_id = $1
`

// Alıcının tüm bildirimlerini siler.
func (q *Queries) DeleteAllNotificationsByRecipient(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllNotificationsByRecipient, recipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM notifications
WHERE id = $1 AND recipient_id = $2
`

type DeleteNotificationParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

// Sahiplik kontrolü: yalnızca alıcıya ait kayıt silinir.
func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotificationsByRecipientOffset = `-- name: ListNotificationsByRecipientOffset :many
SELECT id, recipient_id, title, content, read, created_at, read_at FROM notifications
WHERE recipient_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListNotificationsByRecipientOffsetParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Off         int32     `json:"off"`
	Lmt         int32     `json:"lmt"`
}

func (q *Queries) ListNotificationsByRecipientOffset(ctx context.Context, arg ListNotificationsByRecipientOffsetParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByRecipientOffset, arg.RecipientID, arg.Off, arg.Lmt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Title,
			&i.Content,
			&i.Read,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationsByRecipientOffset = `-- name: ListUnreadNotificationsByRecipientOffset :many
SELECT id, recipient_id, title, content, read, created_at, read_at FROM notifications
WHERE recipient_id = $1
  AND read = FALSE
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListUnreadNotificationsByRecipientOffsetParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Off         int32     `json:"off"`
	Lmt         int32     `json:"lmt"`
}

func (q *Queries) ListUnreadNotificationsByRecipientOffset(ctx context.Context, arg ListUnreadNotificationsByRecipientOffsetParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotificationsByRecipientOffset, arg.RecipientID, arg.Off, arg.Lmt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Title,
			&i.Content,
			&i.Read,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read = TRUE,
    read_at = now()
WHERE recipient_id = $1 AND read = FALSE
`

// Alıcının tüm okunmamış bildirimlerini okundu işaretler.
func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read = TRUE,
    read_at = now()
WHERE id = $1 AND recipient_id = $2 AND read = FALSE
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

// Sahiplik kontrolü: yalnızca alıcıya ait ve okunmamış kayıt güncellenir.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notificationBelongsTo = `-- name: NotificationBelongsTo :one
SELECT EXISTS(SELECT 1 FROM notifications WHERE id = $1 AND recipient_id = $2) AS exists
`

type NotificationBelongsToParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

// Sahiplik doğrulaması (okundu işaretlemede bulunamadı/yetkisiz ayrımı için).
func (q *Queries) NotificationBelongsTo(ctx context.Context, arg NotificationBelongsToParams) (bool, error) {
	row := q.db.QueryRow(ctx, notificationBelongsTo, arg.ID, arg.RecipientID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
