// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	ClearRolePermissions(ctx context.Context, name string) error
	CountActiveUsersByRole(ctx context.Context, role string) (int64, error)
	CountNotificationsByRecipient(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountUsersWithRole(ctx context.Context, role string) (int64, error)
	// auth_tokens: tek kullanımlık süreli token'lar (e-posta doğrulama, şifre sıfırlama).
	// Ham token saklanmaz; yalnızca token_hash (SHA-256) tutulur.
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	// notifications tablosu için type-safe sorgular (uygulama içi bildirimler).
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Dinamik RBAC. İzinler DB'de; roller runtime'da yönetilir.
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	// users tablosu için type-safe sorgular. sqlc bu dosyadan Go kodu üretir.
	// Tüm sorgular parametrelidir ($1, $2 ...) — SQL injection'a karşı birincil savunma.
	// Soft delete: varsayılan okuma sorguları yalnızca deleted_at IS NULL (canlı) kayıtları döner.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Alıcının tüm bildirimlerini siler.
	DeleteAllNotificationsByRecipient(ctx context.Context, recipientID uuid.UUID) (int64, error)
	// Aynı amaçlı önceki token'ları geçersiz kılmak için (yeni token üretilirken).
	DeleteAuthTokensForUser(ctx context.Context, arg DeleteAuthTokensForUserParams) error
	// Periyodik temizlik: süresi dolmuş veya kullanılmış token'ları siler.
	DeleteExpiredAuthTokens(ctx context.Context) error
	// Sahiplik kontrolü: yalnızca alıcıya ait kayıt silinir.
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error)
	// Sistem rolleri (admin/user) silinemez.
	DeleteRole(ctx context.Context, name string) (int64, error)
	// Benzersizlik kontrolü yalnızca canlı kayıtlar üzerinden yapılır; böylece
	// soft-delete edilmiş bir e-posta yeni kayıtta yeniden kullanılabilir.
	ExistsUserByEmail(ctx context.Context, email string) (bool, error)
	GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error)
	GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIDAny(ctx context.Context, id uuid.UUID) (User, error)
	// Batch okuma: N+1 sorgusunu önlemek için tek sorguda birden çok kullanıcı.
	// ANY($1) ile UUID dizisi tek parametre olarak geçirilir.
	GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error)
	// GrantAllPermissionsToRole, verilen role DB'deki tüm izinleri atar (admin senkronu).
	GrantAllPermissionsToRole(ctx context.Context, name string) error
	// Kalıcı (fiziksel) silme. Yalnızca zaten soft-delete edilmiş kayıtlar için;
	// kaza sonucu canlı kaydın kaybını önler (ör. GDPR "kalıcı silme" akışı).
	HardDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	ListNotificationsByRecipientOffset(ctx context.Context, arg ListNotificationsByRecipientOffsetParams) ([]Notification, error)
	ListPermissions(ctx context.Context) ([]ListPermissionsRow, error)
	ListPermissionsForRole(ctx context.Context, name string) ([]string, error)
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	ListUnreadNotificationsByRecipientOffset(ctx context.Context, arg ListUnreadNotificationsByRecipientOffsetParams) ([]Notification, error)
	ListUsersAscKeyset(ctx context.Context, arg ListUsersAscKeysetParams) ([]User, error)
	ListUsersAscOffset(ctx context.Context, arg ListUsersAscOffsetParams) ([]User, error)
	ListUsersDescKeyset(ctx context.Context, arg ListUsersDescKeysetParams) ([]User, error)
	ListUsersDescOffset(ctx context.Context, arg ListUsersDescOffsetParams) ([]User, error)
	// Alıcının tüm okunmamış bildirimlerini okundu işaretler.
	MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) (int64, error)
	// Tek kullanım: yalnızca kullanılmamış ve süresi geçmemiş token işaretlenir.
	MarkAuthTokenUsed(ctx context.Context, id uuid.UUID) (int64, error)
	// Sahiplik kontrolü: yalnızca alıcıya ait ve okunmamış kayıt güncellenir.
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	// Sahiplik doğrulaması (okundu işaretlemede bulunamadı/yetkisiz ayrımı için).
	NotificationBelongsTo(ctx context.Context, arg NotificationBelongsToParams) (bool, error)
	PermissionExists(ctx context.Context, name string) (bool, error)
	// Yazılımsal silmeyi geri alır (deleted_at = NULL).
	RestoreUser(ctx context.Context, id uuid.UUID) (int64, error)
	RoleExists(ctx context.Context, name string) (bool, error)
	// Yazılımsal silme: kaydı fiziksel silmek yerine deleted_at damgalar.
	// Zaten silinmiş kayıtlar etkilenmez (idempotent; execrows=0 → bulunamadı).
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	UpdatePermissionDescription(ctx context.Context, arg UpdatePermissionDescriptionParams) (int64, error)
	UpdateRoleDescription(ctx context.Context, arg UpdateRoleDescriptionParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
