// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = $1 AND p.name = $2
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	Name   string `json:"name"`
	Name_2 string `json:"name_2"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.Name, arg.Name_2)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = (SELECT id FROM roles WHERE name = $1)
`

func (q *Queries) ClearRolePermissions(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, name)
	return err
}

const countUsersWithRole = `-- name: CountUsersWithRole :one
SELECT COUNT(*)::bigint AS count
FROM users
WHERE role = $1 AND deleted_at IS NULL
`

func (q *Queries) CountUsersWithRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :exec

INSERT INTO permissions (id, name, description)
VALUES ($1, $2, $3)
`

type CreatePermissionParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

// Dinamik RBAC. İzinler DB'de; roller runtime'da yönetilir.
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.Exec(ctx, createPermission, arg.ID, arg.Name, arg.Description)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, name, description, is_system)
VALUES ($1, $2, $3, $4)
`

type CreateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsSystem    bool      `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE name = $1 AND is_system = FALSE
`

// Sistem rolleri (admin/user) silinemez.
func (q *Queries) DeleteRole(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT name, description, is_system FROM roles WHERE name = $1
`

type GetRoleByNameRow struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsSystem    bool   `json:"is_system"`
}

func (q *Queries) GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i GetRoleByNameRow
	err := row.Scan(&i.Name, &i.Description, &i.IsSystem)
	return i, err
}

const grantAllPermissionsToRole = `-- name: GrantAllPermissionsToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = $1
ON CONFLICT DO NOTHING
`

// GrantAllPermissionsToRole, verilen role DB'deki tüm izinleri atar (admin senkronu).
func (q *Queries) GrantAllPermissionsToRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, grantAllPermissionsToRole, name)
	return err
}

const listPermissions = `-- name: ListPermissions :many
SELECT name, description FROM permissions ORDER BY name
`

type ListPermissionsRow struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) ListPermissions(ctx context.Context) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsRow{}
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(&i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT p.name
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN roles r ON r.id = rp.role_id
WHERE r.name = $1
ORDER BY p.name
`

func (q *Queries) ListPermissionsForRole(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT name, description, is_system FROM roles ORDER BY name
`

type ListRolesRow struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsSystem    bool   `json:"is_system"`
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(&i.Name, &i.Description, &i.IsSystem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permissionExists = `-- name: PermissionExists :one
SELECT EXISTS(SELECT 1 FROM permissions WHERE name = $1) AS exists
`

func (q *Queries) PermissionExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, permissionExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const roleExists = `-- name: RoleExists :one
SELECT EXISTS(SELECT 1 FROM roles WHERE name = $1) AS exists
`

func (q *Queries) RoleExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, roleExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePermissionDescription = `-- name: UpdatePermissionDescription :execrows
UPDATE permissions SET description = $2 WHERE name = $1
`

type UpdatePermissionDescriptionParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpdatePermissionDescription(ctx context.Context, arg UpdatePermissionDescriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePermissionDescription, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRoleDescription = `-- name: UpdateRoleDescription :execrows
UPDATE roles SET description = $2, updated_at = now() WHERE name = $1
`

type UpdateRoleDescriptionParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpdateRoleDescription(ctx context.Context, arg UpdateRoleDescriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRoleDescription, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
