// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsersByRole = `-- name: CountActiveUsersByRole :one
SELECT COUNT(*)::bigint AS count
FROM users
WHERE role = $1 AND deleted_at IS NULL
`

func (q *Queries) CountActiveUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint AS count
FROM users
WHERE (
        ($1::text IS NULL AND deleted_at IS NULL)
        OR ($1::text = 'only' AND deleted_at IS NOT NULL)
        OR ($1::text = 'all')
      )
  AND ($2::text IS NULL OR role = $2)
  AND ($3::boolean IS NULL OR active = $3)
  AND (
        $4::text IS NULL
        OR name ILIKE '%' || $4 || '%'
        OR email ILIKE '%' || $4 || '%'
      )
`

type CountUsersParams struct {
	Deleted pgtype.Text `json:"deleted"`
	Role    pgtype.Text `json:"role"`
	Active  pgtype.Bool `json:"active"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers,
		arg.Deleted,
		arg.Role,
		arg.Active,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, preferred_locale, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	Name            string             `json:"name"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Active          bool               `json:"active"`
	EmailVerified   bool               `json:"email_verified"`
	MfaEnabled      bool               `json:"mfa_enabled"`
	MfaSecret       string             `json:"mfa_secret"`
	PreferredLocale string             `json:"preferred_locale"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// users tablosu için type-safe sorgular. sqlc bu dosyadan Go kodu üretir.
// Tüm sorgular parametrelidir ($1, $2 ...) — SQL injection'a karşı birincil savunma.
// Soft delete: varsayılan okuma sorguları yalnızca deleted_at IS NULL (canlı) kayıtları döner.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.Active,
		arg.EmailVerified,
		arg.MfaEnabled,
		arg.MfaSecret,
		arg.PreferredLocale,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaLastUsedStep,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1 AND deleted_at IS NULL) AS exists
`

// Benzersizlik kontrolü yalnızca canlı kayıtlar üzerinden yapılır; böylece
// soft-delete edilmiş bir e-posta yeni kayıtta yeniden kullanılabilir.
func (q *Queries) ExistsUserByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaLastUsedStep,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaLastUsedStep,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIDAny = `-- name: GetUserByIDAny :one
SELECT id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByIDAny(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDAny, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaLastUsedStep,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at FROM users WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

// Batch okuma: N+1 sorgusunu önlemek için tek sorguda birden çok kullanıcı.
// ANY($1) ile UUID dizisi tek parametre olarak geçirilir.
func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.EmailVerified,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.MfaLastUsedStep,
			&i.PreferredLocale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteUser = `-- name: HardDeleteUser :execrows
DELETE FROM users WHERE id = $1 AND deleted_at IS NOT NULL
`

// Kalıcı (fiziksel) silme. Yalnızca zaten soft-delete edilmiş kayıtlar için;
// kaza sonucu canlı kaydın kaybını önler (ör. GDPR "kalıcı silme" akışı).
func (q *Queries) HardDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUsersAscKeyset = `-- name: ListUsersAscKeyset :many
SELECT id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at FROM users
WHERE (
        ($1::text IS NULL AND deleted_at IS NULL)
        OR ($1::text = 'only' AND deleted_at IS NOT NULL)
        OR ($1::text = 'all')
      )
  AND ($2::text IS NULL OR role = $2)
  AND ($3::boolean IS NULL OR active = $3)
  AND (
        $4::text IS NULL
        OR name ILIKE '%' || $4 || '%'
        OR email ILIKE '%' || $4 || '%'
      )
  AND (created_at, id) > ($5, $6::uuid)
ORDER BY created_at ASC, id ASC
LIMIT $7
`

type ListUsersAscKeysetParams struct {
	Deleted         pgtype.Text        `json:"deleted"`
	Role            pgtype.Text        `json:"role"`
	Active          pgtype.Bool        `json:"active"`
	Search          pgtype.Text        `json:"search"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	Lmt             int32              `json:"lmt"`
}

func (q *Queries) ListUsersAscKeyset(ctx context.Context, arg ListUsersAscKeysetParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersAscKeyset,
		arg.Deleted,
		arg.Role,
		arg.Active,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lmt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.EmailVerified,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.MfaLastUsedStep,
			&i.PreferredLocale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAscOffset = `-- name: ListUsersAscOffset :many
SELECT id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at FROM users
WHERE (
        ($1::text IS NULL AND deleted_at IS NULL)
        OR ($1::text = 'only' AND deleted_at IS NOT NULL)
        OR ($1::text = 'all')
      )
  AND ($2::text IS NULL OR role = $2)
  AND ($3::boolean IS NULL OR active = $3)
  AND (
        $4::text IS NULL
        OR name ILIKE '%' || $4 || '%'
        OR email ILIKE '%' || $4 || '%'
      )
ORDER BY created_at ASC, id ASC
LIMIT $6 OFFSET $5
`

type ListUsersAscOffsetParams struct {
	Deleted pgtype.Text `json:"deleted"`
	Role    pgtype.Text `json:"role"`
	Active  pgtype.Bool `json:"active"`
	Search  pgtype.Text `json:"search"`
	Off     int32       `json:"off"`
	Lmt     int32       `json:"lmt"`
}

func (q *Queries) ListUsersAscOffset(ctx context.Context, arg ListUsersAscOffsetParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersAscOffset,
		arg.Deleted,
		arg.Role,
		arg.Active,
		arg.Search,
		arg.Off,
		arg.Lmt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.EmailVerified,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.MfaLastUsedStep,
			&i.PreferredLocale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersDescKeyset = `-- name: ListUsersDescKeyset :many
SELECT id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at FROM users
WHERE (
        ($1::text IS NULL AND deleted_at IS NULL)
        OR ($1::text = 'only' AND deleted_at IS NOT NULL)
        OR ($1::text = 'all')
      )
  AND ($2::text IS NULL OR role = $2)
  AND ($3::boolean IS NULL OR active = $3)
  AND (
        $4::text IS NULL
        OR name ILIKE '%' || $4 || '%'
        OR email ILIKE '%' || $4 || '%'
      )
  AND (created_at, id) < ($5, $6::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListUsersDescKeysetParams struct {
	Deleted         pgtype.Text        `json:"deleted"`
	Role            pgtype.Text        `json:"role"`
	Active          pgtype.Bool        `json:"active"`
	Search          pgtype.Text        `json:"search"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	Lmt             int32              `json:"lmt"`
}

func (q *Queries) ListUsersDescKeyset(ctx context.Context, arg ListUsersDescKeysetParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersDescKeyset,
		arg.Deleted,
		arg.Role,
		arg.Active,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lmt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.EmailVerified,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.MfaLastUsedStep,
			&i.PreferredLocale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersDescOffset = `-- name: ListUsersDescOffset :many
SELECT id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at FROM users
WHERE (
        ($1::text IS NULL AND deleted_at IS NULL)
        OR ($1::text = 'only' AND deleted_at IS NOT NULL)
        OR ($1::text = 'all')
      )
  AND ($2::text IS NULL OR role = $2)
  AND ($3::boolean IS NULL OR active = $3)
  AND (
        $4::text IS NULL
        OR name ILIKE '%' || $4 || '%'
        OR email ILIKE '%' || $4 || '%'
      )
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListUsersDescOffsetParams struct {
	Deleted pgtype.Text `json:"deleted"`
	Role    pgtype.Text `json:"role"`
	Active  pgtype.Bool `json:"active"`
	Search  pgtype.Text `json:"search"`
	Off     int32       `json:"off"`
	Lmt     int32       `json:"lmt"`
}

func (q *Queries) ListUsersDescOffset(ctx context.Context, arg ListUsersDescOffsetParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersDescOffset,
		arg.Deleted,
		arg.Role,
		arg.Active,
		arg.Search,
		arg.Off,
		arg.Lmt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.EmailVerified,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.MfaLastUsedStep,
			&i.PreferredLocale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :execrows
UPDATE users
SET deleted_at = NULL,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NOT NULL
`

// Yazılımsal silmeyi geri alır (deleted_at = NULL).
func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Yazılımsal silme: kaydı fiziksel silmek yerine deleted_at damgalar.
// Zaten silinmiş kayıtlar etkilenmez (idempotent; execrows=0 → bulunamadı).
func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2,
    phone = $3,
    name = $4,
    password_hash = $5,
    role = $6,
    active = $7,
    email_verified = $8,
    mfa_enabled = $9,
    mfa_secret = $10,
    preferred_locale = $11,
    updated_at = $12
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, phone, name, password_hash, role, active, email_verified, mfa_enabled, mfa_secret, mfa_last_used_step, preferred_locale, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	Name            string             `json:"name"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Active          bool               `json:"active"`
	EmailVerified   bool               `json:"email_verified"`
	MfaEnabled      bool               `json:"mfa_enabled"`
	MfaSecret       string             `json:"mfa_secret"`
	PreferredLocale string             `json:"preferred_locale"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.Active,
		arg.EmailVerified,
		arg.MfaEnabled,
		arg.MfaSecret,
		arg.PreferredLocale,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MfaLastUsedStep,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
